# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: Bruce_public  ## Cloud private key
instance_flavor: uom.mse.1c4g



# Volume/ can add more
volumes:
  - vol_name: masto-vol-base
    vol_size: 10

# # Security group
security_groups:
  - name: db_tcp  ## for couchdb
    description: "sg for Couchdb access on 5984"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - name: masto-base
    volumes: ["masto-vol-base"]