# - hosts: localhost
#   vars_files:
#     - host_vars/mrc.yaml
#   gather_facts: true

#   roles:
#     # - role: openstack-common
#     - role: openstack-volume
#     - role: openstack-security-group
#     - role: openstack-instance


- hosts: COMP90024
  vars_files:
    - host_vars/server.yaml ## Change this
  gather_facts: true
  
  vars:
  - ansible_user: ubuntu
  - ansible_ssh_private_key_file: ~/ccc/ass2/ansible/cloud.key
  - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    # - role: docker-common
    # - role: docker-volumes
    # - role: docker-install
    # - role: docker-bk_server
    - role: docker-fe_server
    # - role: docker-mastodon
    # - role: docker-remastodon




