# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: Bruce_public  ## Change this to private key name on MRC
instance_flavor: uom.mse.1c4g



# Volume/ can add more
volumes:
  - vol_name: masto_vol_expand
    vol_size: 10

# Security group
security_groups:
  - name: direct_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0



# Instance
instances:
  - name: masto_expand
    volumes: ["masto_vol_expand"]